
language: cpp

addons:
  apt:
    # https://docs.travis-ci.com/user/installing-dependencies#installing-packages-with-the-apt-addon
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - g++-8
      - curl
      - unzip
      - wget
      - rsync
      - cmake
      - ninja-build
  homebrew:
    packages:
      - cmake
      - ninja

cache:
  directories:
    - ${HOME}/vcpkg/installed

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc-8
      before_install:
        - g++-8 --version
        - export CC=gcc-8 CXX=g++-8
      install:
        - bash ./scripts/install-cmake-3.15.sh
        - |
          mkdir -p ${HOME}/vcpkg
          pushd ${HOME}/vcpkg
          git init
          git remote add origin https://github.com/Microsoft/vcpkg.git
          git fetch origin master
          git checkout -b master origin/master
          ./bootstrap-vcpkg.sh
          ./vcpkg install grpc catch2 ms-gsl
          popd
      before_script:
        - mkdir -p build && pushd build
      script:
        - cmake .. -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="${HOME}/vcpkg/scripts/buildsystems/vcpkg.cmake"
      after_script:
        - popd
