git:
  submodules: true
  depth: 3

language: cpp

cache:
  directories:
    - ${HOME}/vcpkg/installed

os: osx

addons:
  homebrew:
    packages:
      - cmake
      - gcc@9
      - python3

matrix:
  include:
    - osx_image: xcode10.3 # macOS 10.14

install:
  - mkdir -p ${HOME}/vcpkg && pushd ${HOME}/vcpkg
  - | # build vcpkg
    git init
    git remote add origin https://github.com/Microsoft/vcpkg.git
    git fetch origin 2019.11
    git checkout FETCH_HEAD
    CC=gcc-9 CXX=g++-9 ./bootstrap-vcpkg.sh
  # install required packages
  - ./vcpkg install ms-gsl tbb grpc gtest
  - popd

script:
  - mkdir -p build && pushd build
  - cmake ..
    -DCMAKE_TOOLCHAIN_FILE="${HOME}/vcpkg/scripts/buildsystems/vcpkg.cmake"
  # codegen and build
  - cmake --build . --config debug

after_success:
  - pip install -r requirements.txt
